import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import packageInfo from './package.json' with { type: 'json'};
import glueGetTable from './glue-get-table.js';
import glueJobTrigger from './glue-job-trigger.js';
import getGlueJobStatus from './get-glue-job-status.js';
import s3Connector from './s3-connector.js';
import athenaQueryExecutor from './athena-query-executor.js';
import log4js from 'log4js';

const l = log4js.getLogger();

// Wrapper function to add comprehensive logging to any MCP tool
const wrapToolWithLogging = (toolArray) => {
  const [toolName, description, schema, originalHandler] = toolArray;
  
  const wrappedHandler = async (args, ctx) => {
    const startTime = Date.now();
    const user = ctx?.authInfo?.user_name || ctx?.auth?.user_name || "unknown user";
    
    console.log(`🔧 MCP TOOL CALLED: ${toolName}`);
    console.log(`👤 User: ${user}`);
    console.log(`📋 Arguments:`, JSON.stringify(args, null, 2));
    console.log(`⏰ Timestamp: ${new Date().toISOString()}`);
    
    try {
      const result = await originalHandler(args, ctx);
      const duration = Date.now() - startTime;
      
      console.log(`✅ MCP TOOL SUCCESS: ${toolName} (${duration}ms)`);
      console.log(`📤 Result type: ${result?.content?.[0]?.type || 'unknown'}`);
      console.log(`📤 Result length: ${JSON.stringify(result).length} chars`);
      
      return result;
    } catch (error) {
      const duration = Date.now() - startTime;
      
      console.error(`❌ MCP TOOL ERROR: ${toolName} (${duration}ms)`);
      console.error(`❌ Error message: ${error.message}`);
      console.error(`❌ Error code: ${error.code}`);
      console.error(`❌ Error stack:`, error.stack);
      
      // Re-throw the error to maintain original behavior
      throw error;
    }
  };
  
  return [toolName, description, schema, wrappedHandler];
};

const create = () => {
  const mcpServer = new McpServer({
    name: `DQ-mcp`,
    version: packageInfo.version
  }, {
    capabilities: {
      tools: {}
    },
    instructions: `
This MCP Server provides 
1. Tools to connect to S3 and Glue
2. Tools to run queries generated by Agent in Glue
`
  });

  console.log(`🚀 Registering MCP tools with comprehensive logging...`);
  
  // Register all tools with logging wrapper
  mcpServer.tool(...wrapToolWithLogging(glueGetTable));
  mcpServer.tool(...wrapToolWithLogging(glueJobTrigger));
  mcpServer.tool(...wrapToolWithLogging(getGlueJobStatus));
  mcpServer.tool(...wrapToolWithLogging(s3Connector));
  mcpServer.tool(...wrapToolWithLogging(athenaQueryExecutor));
  
  console.log(`✅ All MCP tools registered with logging (including fast Athena executor)`);
  
  return mcpServer
};

export default { create };
